[project]
name = "supcheck"
version = "1.1.1"
license = { file = "LICENCE" }
dependencies = [
    "lxml",
    "pyside6-essentials",
    "saxonche",
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = ["pytest", "pyinstaller", "types-lxml"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

# these are entry points for the command line
[project.scripts]
an_report = "supcheck.added_names_report:main"
compare_report = "supcheck.compare_amendment_documents:main"
startgui = "supcheck.supcheck_gui:main"
compare_bills = "supcheck.compare_bill_documents:main"

[tool.isort]
profile = "black"
force_to_top = ["supcheck.supcheck_logger"]
