# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/addedNames.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(527, 292)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.AddedNamesReport = QtWidgets.QWidget()
        self.AddedNamesReport.setObjectName("AddedNamesReport")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.AddedNamesReport)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.get_label = QtWidgets.QLabel(self.AddedNamesReport)
        self.get_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.get_label.setObjectName("get_label")
        self.gridLayout.addWidget(self.get_label, 0, 0, 1, 1)
        self.openBrowser_btn = QtWidgets.QPushButton(self.AddedNamesReport)
        self.openBrowser_btn.setObjectName("openBrowser_btn")
        self.gridLayout.addWidget(self.openBrowser_btn, 0, 1, 1, 1)
        self.instruction_label = QtWidgets.QLabel(self.AddedNamesReport)
        self.instruction_label.setWordWrap(True)
        self.instruction_label.setObjectName("instruction_label")
        self.gridLayout.addWidget(self.instruction_label, 1, 0, 1, 2)
        self.select_label = QtWidgets.QLabel(self.AddedNamesReport)
        self.select_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.select_label.setObjectName("select_label")
        self.gridLayout.addWidget(self.select_label, 2, 0, 1, 1)
        self.xmlFile_btn = QtWidgets.QPushButton(self.AddedNamesReport)
        self.xmlFile_btn.setObjectName("xmlFile_btn")
        self.gridLayout.addWidget(self.xmlFile_btn, 2, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.run_btn = QtWidgets.QPushButton(self.AddedNamesReport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_btn.sizePolicy().hasHeightForWidth())
        self.run_btn.setSizePolicy(sizePolicy)
        self.run_btn.setMaximumSize(QtCore.QSize(264, 16777215))
        self.run_btn.setObjectName("run_btn")
        self.verticalLayout_2.addWidget(self.run_btn, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.AddedNamesReport, "")
        self.CheckFM = QtWidgets.QWidget()
        self.CheckFM.setObjectName("CheckFM")
        self.tabWidget.addTab(self.CheckFM, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Added Names Report"))
        self.get_label.setText(_translate("MainWindow", "Get dashboard XML:"))
        self.openBrowser_btn.setText(_translate("MainWindow", "Open in Browser"))
        self.instruction_label.setText(_translate("MainWindow", "The above button should open the added names dashboard in a web browser.  You must download and save the XML to your computer and then use the below button to allow this app to read the XML file."))
        self.select_label.setText(_translate("MainWindow", "Select dashboard XML:"))
        self.xmlFile_btn.setText(_translate("MainWindow", "Open File"))
        self.run_btn.setText(_translate("MainWindow", "Create Added Names Report"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AddedNamesReport), _translate("MainWindow", "Added Names Report"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CheckFM), _translate("MainWindow", "Check names in FM"))
